site_name: ChatGPT For Teachers
site_description: 'Resources for showing teachers how to use ChatGPT to generate curriculum.  All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
repo_url: 'https://github.com/CoderDojoTC/chatgpt-for-teachers'

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Concepts:
    - Intro: concepts/index.md
    - Ethics: concepts/ethics.md
    - Prompts: concepts/prompts.md
    - Tokens: concepts/tokens.md
    - Output Formats: concepts/output-formats.md
    - Abstraction: concepts/abstraction.md
  - Basic Prompts:
    - Intro: prompts/index.md
    - Syllabus: prompts/01-syllabus.md
    - Code of Conduct: prompts/02-code-of-conduct.md
    - Concept Graph: prompts/08-concept-graph.md 
    - License: prompts/03-license.md
    - License Footer: prompts/04-license-footer.md
    - Mkdocs Config: prompts/05-mkdocs.md
    - Lessons: prompts/06-lessons.md
    - Scratch: prompts/09c-scratch-block.md
    - Sample Code: prompts/09-sample-code.md
    - Turtle Graphics: prompts/09a-turtle-graphics.md
    - Rainbow Boxes: prompts/09b-rainbow-boxes.md
    - HTML: prompts/10-html.md
    - Slope and Intercept: prompts/10-slope-and-intercept.md
    - SVG: prompts/11-svg.md
    - Debugging: prompts/12-debugging.md
    - Explaining Code: prompts/17-explaining-code.md
  - Intermediate Prompts:
    - Designing Robots: prompts/18-designing-robots.md
    - Comparing Microcontrollers: prompts/19-comparing-microcontrollers.md
    - Charts and Plotting: prompts/13-charts.md
    - List: prompts/22.lists.md
    - Tables: prompts/14-tables.md
    - Scatter Plots: prompts/21-scatter-plots.md
    - Dataframes: prompts/23-dataframes.md
    - NumPy: prompts/24-numpy.md
    - Linear Regression: prompts/25-linear-regression.md
    - SciKit Learn: prompts/25-scikit-learn.md
    - Glossary: prompts/07-glossary.md
    - prompts/16-quiz.md 
  - Tips and Tricks: tips-and-tricks.md
  - Advanced Topics:
    - Intro: advanced-topics/index.md
    - advanced-topics/alternatives.md
    - advanced-topics/classification.md
    - advanced-topics/costs.md
    - advanced-topics/embeddings.md
    - advanced-topics/fine-tuning.md
    - prompts/15-micropython.md
    - prompts/20-website-analytics.md
    - prompts/26-systems-thinking.md
  - Interactive Demos:
    - Intro: demos/index.md
    - P5.js Demos: demos/p5/index.md
  - The Future of AI:
    - Introduction: future/index.md
    - Today: future/ai-today.md
    - Near Term: future/near-term.md
    - Long Term: future/long-term.md

  - Slides: slides.md
  - Glossary: glossary.md
  - Markdown Summary: markdown-summary.md
  - References: references.md
  - Contacts: contacts.md
  
copyright: # should remain a link to the original theme
   <div>
     <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.
   </div>
# CoderDojo Microsite Standards from here down

edit_uri: 'blob/master/docs'
theme:
  # should be name: material
  language: en
  name: material
  logo: img/code-savvy-logo.png
  favicon: img/code-savvy-logo.png
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  custom_dir: 'theme'
  include_sidebar: true
  features:
    - navigation.footer
  extra:
    generator: false
    custom_dir: theme/
plugins:
  - search
  # - mermaid2 - takes too long to build - use a screen image for now
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - footnotes
  - codehilite

extra:
  analytics:
    provider: google
    property: G-20VNY7Q9TB

