site_name: Generative AI for Teachers
site_description: 'Resources for showing teachers how to use ChatGPT to generate curriculum.  All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
repo_url: 'https://github.com/CoderDojoTC/chatgpt-for-teachers'

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Concepts:
    - Intro: concepts/index.md
    - Ethics: concepts/ethics.md
    - Prompts: concepts/prompts.md
    - Tokens: concepts/tokens.md
    - Output Formats: concepts/output-formats.md
    - Abstraction: concepts/abstraction.md
  - Basic Prompts:
    - Intro: prompts/index.md
    - Syllabus: prompts/01-syllabus.md
    - Code of Conduct: prompts/02-code-of-conduct.md
    - Concept Graph: prompts/08-concept-graph.md 
    - License: prompts/03-license.md
    - License Footer: prompts/04-license-footer.md
    - Mkdocs Config: prompts/05-mkdocs.md
    - Lessons: prompts/06-lessons.md
    - Scratch: prompts/09c-scratch-block.md
    - Sample Code: prompts/09-sample-code.md
    - Turtle Graphics: prompts/09a-turtle-graphics.md
    - Rainbow Boxes: prompts/09b-rainbow-boxes.md
    - HTML: prompts/10-html.md
    - Slope and Intercept: prompts/10-slope-and-intercept.md
    - SVG: prompts/11-svg.md
    - Debugging: prompts/12-debugging.md
    - Explaining Code: prompts/17-explaining-code.md
  - Intermediate Prompts:
    - Designing Robots: prompts/18-designing-robots.md
    - Comparing Microcontrollers: prompts/19-comparing-microcontrollers.md
    - Charts and Plotting: prompts/13-charts.md
    - List: prompts/22.lists.md
    - Tables: prompts/14-tables.md
    - Scatter Plots: prompts/21-scatter-plots.md
    - Dataframes: prompts/23-dataframes.md
    - NumPy: prompts/24-numpy.md
    - Linear Regression: prompts/25-linear-regression.md
    - SciKit Learn: prompts/25-scikit-learn.md
    - Systems Thinking: prompts/26-systems-thinking.md
    - Regression Line: prompt/27-regression-line.md
    - Glossary: prompts/07-glossary.md
    - prompts/16-quiz.md 
  - Tips and Tricks: tips-and-tricks.md
  - Advanced Topics:
    - Intro: advanced-topics/index.md
    - advanced-topics/alternatives.md
    - advanced-topics/classification.md
    - advanced-topics/costs.md
    - advanced-topics/embeddings.md
    - advanced-topics/fine-tuning.md
    - prompts/15-micropython.md
    - prompts/20-website-analytics.md
    - prompts/21-scatter-plots.md
    - prompts/22-lists.md


    - prompts/26-systems-thinking.md
    - prompts/27-regression-line.md
    - advanced-topics/data-analysis.md
  - Interactive Demos:
    - Intro: demos/index.md
    - JavaScript:
      - Journey Map: demos/js-graphics/journey-map.html
      - Journey Map Labels: demos/js-graphics/journey-map-labels.html
      - Journey Map 3: demos/js-graphics/journey-map-3.html
    - p5.js Animations:
      - Introduction: demos/p5/index.md
      - Sketch Structure: demos/p5/sketch-structure.md
      - Prompt Templates: demos/p5/prompt-templates.md
      - Circle Slider: demos/p5/circle-slider.md
      - Dual Sliders: demos/p5/sliders.md
      - Polygon: demos/p5/polygon.md
      - Star: demos/p5/star.md
      - Slope and Intercept: demos/p5/slope.md
      - Sine Wave: demos/p5/sine.md
      - Pulse-Width Modulation: demos/p5/pwm.md
      - Wave Sums: demos/p5/wave-sums.md
      - Rainbow Tree: demos/p5/rainbow-tree.md
      - Conway's Game of Life: demos/p5/conways-life.md
      - Brownian Motion: demos/p5/brownian-motion.md
      - Least Squares Fit: demos/p5/least-squares-fit.md
      - Electrical Switch: demos/p5/switch.md
      - Wire Animation: demos/p5/wire-animate.md
      - Battery Circuit: demos/p5/battery-circuit.md
      - H-Bridge Circuit: demos/p5/h-bridge.md
      - Rotating Motor: demos/p5/motor.md
      - Logic Gates: demos/p5/logic-gates.md
      - Arithmetic Logic Unit: demos/p5/alu.md
      - The Office DVD Logo: demos/p5/the-office-dvd-logo.md
      - 7-Segment Display: demos/p5/7-segment-display.md
      - Analog Clock Face: demos/p5/analog-clock-face.md
      - Neural Network: demos/p5/neural-network.md
      - Least Squares Fit: demos/p5/least-square-fit.md
      - Reference Frames: demos/p5/reference-frames.md
      - Slope and Intercept: demos/p5/slope-and-intercept.md
  - The Future of AI:
    - Introduction: future/index.md
    - Today: future/ai-today.md
    - Near Term: future/near-term.md
    - Long Term: future/long-term.md

  - Slides: slides.md
  - Glossary: glossary.md
  - Markdown Summary: markdown-summary.md
  - References: references.md
  - Contacts: contacts.md
  
copyright: # should remain a link to the original theme
   <div>
     <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.
   </div>
# CoderDojo Microsite Standards from here down

edit_uri: 'blob/master/docs'
theme:
  # should be name: material
  language: en
  name: material
  logo: img/code-savvy-logo.png
  favicon: img/code-savvy-logo.png
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  custom_dir: 'theme'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
  extra:
    generator: false
    custom_dir: theme/
plugins:
  - search
  # - mermaid2 - takes too long to build - use a screen image for now
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - footnotes
  - codehilite

extra:
  analytics:
    provider: google
    property: G-20VNY7Q9TB

